<a href="https://colab.research.google.com/github/edgar155/unidad1/blob/main/practica7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Edgar valerio valenzuela - Practica 7 - 25 de
septiembre de 2025.
-------------------
slicing NumPy
-------------------
Utilize STEP para determinar el paso del corte:

Ejemplo: ([1,2,3,4,5,6,7]) - Devuelve todos los elementos del indice 5

In [ ]:
arreglo = np.array([1,2,3,4,5,6,7])
print (arreglo[1:5:2])

Ejemplo 2 :([1,2,3,4,5,6,7]) Devuelve los elementos de la matriz

```
# This is formatted as code
```



In [ ]:
import numpy as np
arreglo = np.array([1,2,3,4,5,6,7])
print(areglo[::2])

slice de matrices 2D
---------------
Ejemplo: ([[1,2,3,4,5], [6,7,8,9,10]])
Del segundo elemento , corte del indice 1 al
indice 4

In [2]:
import numpy as np
arreglo = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[1, 1:4])

[7 9]


Ejemplo 4:([[1,2,3,4,5],[6,7,8,9,10]])
De ambos elementos , devueve el indice 2
---------------------

In [4]:
import numpy as np
arreglo = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[0:2, 2])

[3 8]


Ejemplo 5 : ([[1,2,3,4,5],[6,7,8,9,10]])
De ambos elemntos , corta el indice 1 al
indice 4.
-------------

In [6]:
import numpy as np
arreglo = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arreglo[0:2,1: 4])

[[2 3 4]
 [7 8 9]]


Ejercicio 1 - Autonomo
Del siguente arreglo , ¿cual es el siguente resultado?
([1,2,3,4,5,6,7])
corta del 1er elemento al 6to elemento con paso 2

In [13]:
import numpy as np
arreglo = np.array([1,2,3,4,5,6,7])
print(arreglo[0:6:2 ])

[1 3 5]
